deployments:
  Magento:
    filename:
      ./docker-compose.yml
    auto_deploy_on_commits:
      true
    auto_deploy_ttl:
      1h
    post_launch:
      - target: web
        command: exec
        options: "{target} 'sleep 10;install-magento'"
