deployments:
  Magento:
    filename:
      ./docker-compose.yml
    auto_deploy_on_commits:
      true
    auto_deploy_ttl:
      1h
    auto_deploy_post_launch_commands:
      Install:
        web:
          - install-magento
