deployments:
  Magento:
    filename:
      ./docker-compose.yml
    auto_deploy_on_commits:
      true
    wait_post_launch:
      true
    post_launch:
      - target: web
        command: exec
        options: "{target} sh -c 'install-magento'"
